#!/bin/bash
CC	= arm-linux-gnueabihf-gcc
CFLAGS	= -O1 -Wall
LDFLAGS = -fno-stack-protector

objects	= fibseq.o fib.o

default: fibseq

.PHONY: default clean qemu

fibseq: $(objects)
	$(CC) $(LDFLAGS) -o $@ $^

fib.o: fib.s
fibseq.o: fibseq.c

%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

%.o: %.s
	$(CC) -c $(CFLAGS) -o $@ $<

clean:
	rm -f $(objects) fibseq

QEMU_CMD = qemu-arm -L /usr/arm-linux-gnueabihf ./fibseq &
CMD = yes 9 | $(call QEMU_CMD) && sleep 1
qemu: fibseq
	num=1 ; a0=0 ; a1=1;\
	while [ $$num -le 46 ] ; do \
		ans=`yes $$num | $(call QEMU_CMD)` ;\
		sleep 1 ;\
		echo $$ans ; \
		ans=`echo $$ans | cut -d ' ' -f 7`;\
		a2=`expr $$a1 + $$a0`;\
		if [ "$$a1" -eq "$$ans" ] ; then\
			echo "correct";\
		else\
			echo "wrong";\
		fi;\
		a0=$$a1;\
		a1=$$a2;\
		num=`expr $$num + 1`;\
	done
